### PR TITLE
form page 4

### PR DESCRIPTION
**Pull request by ymloh**
[Trello card](https://trello.com/c/Wv2qDZ21/167-dev-sml-update-page-4-of-form-to-reflect-updated-wireframe)

Quick work using the approved pages as template code!

@batteries76 @hqtan The spacing is off on all the pages we've made progress on so far. Would it be okay to address this for all 5 pages in a separate Trello card?

#### Figma layout:
Figma layout

#### Current layout:
Current layout

### CODE REVIEW

**Review by batteries76 — APPROVED** [review]
Looks spot on, Meng - although I admit this is just from reading the code.
Thinking about it now, now that I'm in the swing a bit more, I want to get the full app set up so that I can test more than just the UI. But also in keeping with how we've been going, I'm more than happy to approve, as that aspect is looking very good.

**Comment by hqtan** [comment]
HI @ymloh ,

nice work on the changes! :+1: 

I've tried the [preview app on this link](https://council-emissions-calculator-spike-git-fork-439cc8-civic-makers.vercel.app/), and noticed an issue:

the free-text response isn't getting saved and submitted to the [spreadsheet](https://docs.google.com/spreadsheets/d/1d4UQSXPPOcjFtu7RkJsh6DvhRKt11xVCW8WyTC8GeqE/edit?usp=sharing)

I noticed in the `POST` request to `api/sheeter` that `incentive` variable hasn't captured text responses (see screenshot)

image

 Can you confirm the issue with the preview app, and provide a fix?
 
 Thx @ymloh ! :bow:

**Comment by batteries76** [comment]
As if on queue the nagging worry I had comes up.
Good catch @hqtan, and good work @ymloh.

**Comment by hqtan** [comment]
ooooo I love your work @ymloh :heart_eyes: 
Thx for the fix! :bow: 

lovely jubbly

**Comment by hqtan** [comment]
[DEV: [SML] update page 4 of form to reflect updated wireframe](https://trello.com/c/Wv2qDZ21/167-dev-sml-update-page-4-of-form-to-reflect-updated-wireframe)

**Pull request merged**
