### PR TITLE
Change travel method casing

### PR DESCRIPTION
**Pull request by OlaShabalina**
## Overview of the Pull Request:
- Change travel method button casing to sentence one;
- Change the results Page (that data is displayed on the charts, thought it's good to make it consistent);

Had doubdts about choice options (`Xxxxx/Yyyyy`, example `Walk/Run`), if we keen all words in selection capital it's called title case, not the sentence case. For proper sentence casing only first letter in a sentence is capital. 

On a separate note, while working on the card, I realised the chart headers also have inconsistent casing. New card is created here: https://trello.com/c/QlMmOXCT

## link to Trello card or Github issue
Trello card: https://trello.com/c/bIR3LFt9

## How Has This Been Tested?
- Check the page for travel method selection (form has to be filled to reach the page): https://council-emissions-calculator-spike-git-5ee477-codeforaustralia.vercel.app
- CHeck the results page: https://council-emissions-calculator-spike-git-5ee477-codeforaustralia.vercel.app/results 

## Pull Request Checklist:

Make sure the following checkboxes`[ ]` are checked with `x` before sending your PR -- thank you!

- [x] Have you included a link Trello card / Github issue and written sufficient description to help others review your work?
- [x] Is your pull request up-to-date with `main` branch?
- [x] Have you checked That code is well formatted? Did `npx prettier --check .` return no warnings/errors?
- [x] Have you written instructions on how to test that your changes work as expected?
- [x] Have you tested your work thoroughly on your local machine to ensure you are not breaking anything?

### CODE REVIEW

**Comment by OlaShabalina** [comment]
[Update casing for Transport button text](https://trello.com/c/bIR3LFt9/60-update-casing-for-transport-button-text)

**Comment by Amutha37** [comment]
Great work Olga. I left a comment for image before and after in trello for this PR.

**Comment by Amutha37** [comment]
Great work Olga.   In our case i the survey question started with capital and the selection followed should be lower case. It is almost like a follow on answer not in long sentence but single word.

That is an option but with the way we have set it now is just fine. I think it will look odd if we leave all the buttons in lower case. 
Think about it anyway, for rules also.

**Comment by OlaShabalina** [comment]
> Great work Olga. In our case i the survey question started with capital and the selection followed should be lower case. It is almost like a follow on answer not in long sentence but single word.
> 
> That is an option but with the way we have set it now is just fine. I think it will look odd if we leave all the buttons in lower case. Think about it anyway, for rules also.

I agree it would look strange to have all buttons starting from lower case letter. I think the idea is that each button in isolation is a separate component with sentence case text. So it starts from capital always.

**Review by hqtan — APPROVED** [review]
lgtm 👍🏽 

Thanks @OlaShabalina ! 🚀

**Pull request merged**
