### PR TITLE
add sheeter api to access Google Sheets

### PR DESCRIPTION
**Pull request by hqtan**
The main purpose of this PR is to add the `sheeter` API route to app, which will be used to access Google Sheets.

- add sheeter api as an API route
  see: https://nextjs.org/docs/api-routes/introduction
- updated `utils/dbApi` to use sheeter API route
- add googleapi library in `package.json` for sheeter api route
- update next.js in `package.json` for security updates

### CODE REVIEW

**Comment by batteries76** [comment]
Hey Qing @hqtan,
All looks good, but I'll have to do a bit of research/have a run through of the code at some point.
Might be able to find a time, and @ymloh might be interested too?

**Comment by hqtan** [comment]
Hi @batteries76, @ymloh,

It might help to understand the How, What and Why's of the `sheeter` API, so here it is:

## Rationale for creating `sheeter` API (henceforth referred to as just 'API', or 'API route'):
- `sheeter` is an interface to [Google Sheets API](https://googleapis.dev/nodejs/googleapis/latest/sheets/index.html). It uses the `googleapi/sheets` npm submodule to access Google Sheets, and Nextjs' [API route framework](https://nextjs.org/docs/api-routes/introduction)

- An alternative approach to accessing Google Sheets was considered: there's a javascript client library that can be run on the browser end to do the same thing, which I did use in an earlier spike; but providing the necessary creds to access the Google Sheet used to store all form responses meant one of two things:
  - 'hardcoding' API creds into the frontend code, or
  - asking users to log in with their Google user to fill in form (and then having to authorize each user to make changes to Google Sheets).
  Neither of those seemed like appealing options at the time. For that reason, I chose to implement a 'backend' solution with a node.js API (using nextjs' [API route framework](https://nextjs.org/docs/api-routes/introduction), which simplified things a lot)

- the API has the necessary creds to access a Google Sheet. The creds are passed in via this environment variable: `GCP_APP_CREDS` (refer to [pages/api/sheeter.js:L20](https://github.com/CodeforAustralia/council-emissions-calculator-spike/pull/13/files#diff-ecbf0d07f4806aff433e0a67f2978520385a5c710d3cf64cf5442a7339a3ceebR20)). More info about how the creds are generated later
  - the `GCP_APP_CREDS` environment variable is set in Vercel. Vercel will pass this env var in to the app's runtime enviroment

- the ID of the Google Sheet that the API accesses is currently 'hardcoded' in (see [pages/api/sheeter.js:L61](https://github.com/CodeforAustralia/council-emissions-calculator-spike/pull/13/files#diff-ecbf0d07f4806aff433e0a67f2978520385a5c710d3cf64cf5442a7339a3ceebR61)) :scream:. The hardcoding is not ideal; a better solution exists

- for more info on how to use the `googleapi` nodejs library to access Google Sheets, refer to these docs:
  - [Reading & Writing Cell Values](https://developers.google.com/sheets/api/guides/values)
  - [example code](https://github.com/googleapis/google-api-nodejs-client/tree/master/samples/sheets)

- The `sendFormResponse()` and `getFormResponses()` functions in `utils/dbApi.js` calls the API route to submit or retrieve form responses
  - `getFormResponses()` currently retrieves all form responses from Google Sheet; I suspect we won't need to do that in futre, and will only require to retrieve the results of calculations performed on the form data.

**Comment by hqtan** [comment]
## How to test the API Route

There are a couple of approaches I can think of to test the API route:
1. (easiest) directly using the Preview site, and hitting the api endpoint
2. running the api endpoint locally (requires creds to access Google Sheets)

### Testing using the Preview site

- A link to the Preview site that Vercel deploys for testing will be in a comment in the PR (see [this comment](https://github.com/CodeforAustralia/council-emissions-calculator-spike/pull/13#issuecomment-910895706)).

- The endpoint for api route will be `https://[Preview link]/council-emissions-calculator-spike/api/sheeter`. Some example `curl` commands are provided below to test with the api. You can also use other tools like Postman and Insomnia, or even test with your browser's Developer tools console with `fetch()` commands.

- Some test data you can submit to Google Sheets:
```
$ cat test-form-response.json
{
  "km": "42",
  "week": ["office", "home", "home", "office", "office", "didNotWork", "didNotWork"],
  "transportModes": ["bike", "didNotTravel", "didNotTravel", "bus", "bus", "didNotTravel", "didNotTravel"],
  "incentive": "I'd like to have better biking lanes.",
  "department": "Education"
}
```

- [Link to Google Sheet](https://docs.google.com/spreadsheets/d/1d4UQSXPPOcjFtu7RkJsh6DvhRKt11xVCW8WyTC8GeqE/edit?usp=sharing)
  - You might not have access to view spreadsheet. Reach out to me if you'd like access to view Google Sheet

## Sample `curl` commands

- To retrieve all form responses using a `curl` command:
```
$ curl https://council-emissions-calculator-spike-git-add-29bc37-civic-makers.vercel.app/council-emissions-calculator-spike/api/sheeter
{"range":"'Form Responses 1'!A13:P156","majorDimension":"ROWS","values":[...]}
```

- To submit a form response using a `curl` command:
```
$ curl -X POST -H 'Content-Type: application/json' -d '' https://council-emissions-calculator-spike-git-add-29bc37-civic-makers.vercel.app/council-emissions-calculator-spike/api/sheeter
{"spreadsheetId":"1d4UQSXPPOcjFtu7RkJsh6DvhRKt11xVCW8WyTC8GeqE","tableRange":"'Form Responses 1'!A13:Q44","updates":{"spreadsheetId":"1d4UQSXPPOcjFtu7RkJsh6DvhRKt11xVCW8WyTC8GeqE","updatedRange":"'Form Responses 1'!A45"}}
```

- submit the form response stored in a file called `test-form-response.json` using a `curl` command:
```
$ curl -X POST -H 'Content-Type: application/json' -d @test-form-response.json https://council-emissions-calculator-spike-git-add-29bc37-civic-makers.vercel.app/council-emissions-calculator-spike/api/sheeter
{"spreadsheetId":"1d4UQSXPPOcjFtu7RkJsh6DvhRKt11xVCW8WyTC8GeqE","tableRange":"'Form Responses 1'!A13:Q44","updates":{"spreadsheetId":"1d4UQSXPPOcjFtu7RkJsh6DvhRKt11xVCW8WyTC8GeqE","updatedRange":"'Form Responses 1'!A45:Q45","updatedRows":1,"updatedColumns":17,"updatedCells":17}}
```

## N.B: Things to note:
- The form data is stored in a json object. Google Sheets needs the data as a list of strings. The api does this 'conversion' using `convertFormResponseToList()` (see [`pages/api/sheeter.js`:L98](https://github.com/CodeforAustralia/council-emissions-calculator-spike/pull/13/files#diff-ecbf0d07f4806aff433e0a67f2978520385a5c710d3cf64cf5442a7339a3ceebR98-R117))
- There is currently no validation of form responses before it is submitted to Google Sheets! :scream: This is a tech debt that we'll have to address.

**Comment by hqtan** [comment]
### Testing API Route locally
- Assumption: some familiarity working in a terminal
- You will need creds in order to access the Google Sheet. Ask @hqtan for them!
- Once you've obtained the creds, export them as an environment variable:
```
export GCP_APP_CREDS=$(cat /path/to/creds.json)
```
- `cd` to your working copy of app repo, and run npm dev environment:
```
$ cd council-emissions-calculator-spike/
$ npm run dev
```
- if everything was successful, the api route will be accessible on `http://localhost:3000/api/sheeter`:
```
$ curl http://localhost:3000/api/sheeter
{"range":"'Form Responses 1'!A13:P156","majorDimension":"ROWS","values":[...]}
```
- tweak the above mentioned sample `curl` commands to submit form responses

**Comment by hqtan** [comment]
### Creating own testing environment from scratch
This involves:
- creating a GCP project, and enable Google Sheets API
- generating a service account key for GCP project's default service account
- creating a Google Sheet, and granting service account access to it
Once you have successfully completed the above 3 steps, follow the instructions
for ['Testing API Route locally'](https://github.com/CodeforAustralia/council-emissions-calculator-spike/pull/13#issuecomment-912128641) to run API Route locally.


#### creating a GCP project, and enable Google Sheets API
[follow the instructions here to create a GCP project and enable Google Sheets API](https://developers.google.com/workspace/guides/create-project)
- when a new GCP project is created, a default service account should also be created. We will use this default service account to access Google Sheets
- read more about service accounts [here](https://cloud.google.com/iam/docs/service-accounts)


#### generating a service account key for GCP project's default service account
[follow the instructions in this doc to create a service account key](https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating_service_account_keys)
- the contents of the service account key will be stored in the `GCP_APP_CREDS` environment variable later


#### creating a Google Sheet, and granting service account access to it
- create a Google Sheet using the [Sheets console](https://docs.google.com/spreadsheets/), or via the [Sheets API](https://developers.google.com/sheets/api/guides/create)
- follow [instructions here](https://support.google.com/drive/thread/12975286/google-sheets-sharing-with-edit-privileges?hl=en) to share Google Sheet with service account
- you will need to find your service account's email in order to grant service account access to Google Sheet. You can find it [here](https://console.cloud.google.com/iam-admin/serviceaccounts). It should be of the form `[YOUR_GCP_PROJECT_NAME]@appspot.gserviceaccount.com`

**Review by ymloh — APPROVED** [review]
I don't know enough about the sheets API, but the blocks I can make sense of look perfectly sound to me!

**Comment by hqtan** [comment]
> I don't know enough about the sheets API, but the blocks I can make sense of look perfectly sound to me!

Thx for the :heavy_check_mark: @ymloh !

The code does the job atm, but there are certainly some big warts there that I'd want to come back later to fix. I've registered those accrued 'tech debts' in our [tech debt Trello card](https://trello.com/c/DmGDjFt9/154-dev-post-mvp-todos-aka-tech-debt). Feel free to add any other issues that we should circle back to in that card!

**Pull request merged**
