### PR TITLE
Fix alignment for all components(sections) on the results page

### LINKED ISSUE #216: Fix alignment for all components(sections) on the results page
## I'm submitting a ...

- bug report

## What is the current behavior?

Sections have different alignment (example - first section is center aligned, top three - is left aligned, etc);

image

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

* Open browser and go to https://council-emissions-calculator-spike-flax.vercel.app/results
* Open toggle device toolbar and choose mobile

## What is the expected behavior?

- [ ] each section is center aligned 
- [ ] each section has the same margins and padding from both sides.

## Solution

Change alignment for the section to be consistent of mobile.

## What is the motivation / use case for changing the behavior?

Responsiveness on mobile.

**Link to Trello card:** [here](https://trello.com/c/hqw5CLOC)

### PR DESCRIPTION
**Pull request by hqtan**
Fixes #216

## Overview of the Pull Request:
see issue #216 and the Trello card for more details

## link to Trello card or Github issue
https://trello.com/c/hqw5CLOC

## How Has This Been Tested?
reviewer should verify using the preview deployment that the results page in desktop and mobile view satisfies the following:
* each section is center aligned
* each section has the same margins and padding from both sides.

**N.B:** The stacked bar chart in the 'Distance travelled by mode of transport' section, and bubble chart in the 'Staff Suggestions' section will not fit nicely in a narrow mobile viewport. The accommodate them, I have set `overflowX="auto` on the Flex boxes containing those graphs, so the user can scroll to the left/right to view the rest of the graphs. We may need to discuss this further with design team.

## Pull Request Checklist:

Make sure the following checkboxes`[ ]` are checked with `x` before sending your PR -- thank you!

- [x] Have you included a link Trello card / Github issue and written sufficient description to help others review your work?
- [x] Is your pull request up-to-date with `main` branch?
- [x] Have you checked That code is well formatted? Did `npx prettier --check .` return no warnings/errors?
- [x] Have you written instructions on how to test that your changes work as expected?
- [x] Have you tested your work thoroughly on your local machine to ensure you are not breaking anything?

### CODE REVIEW

**Comment by OlaShabalina** [comment]
Hi @hqtan , I can see you did a lot of work on this one, well done!
The card under distance graph got stretched here: 
image

**Review by OlaShabalina — CHANGES_REQUESTED** [review]
Hi @hqtan , I can see you did a lot of work on this one, well done!
The card under distance graph got stretched here: 
image

**Comment by hqtan** [comment]
> Hi @hqtan , I can see you did a lot of work on this one, well done! The card under distance graph got stretched here: 

Ooooh good catch @OlaShabalina ! 🙌🏽 
I think I've sorted it out; lemme know what you think 🙏🏽

**Comment by OlaShabalina** [comment]
@hqtan , and now it looks strange on mobile, what do you think?
image

**Comment by hqtan** [comment]
> @hqtan , and now it looks strange on mobile, what do you think?

Hi @OlaShabalina ,
This stacked bar chart was tricky to fit into the width of a mobile viewport.
I lacked the HighCharts-fu to make that chart type scale to fit nicely on a mobile screen, given the time I had.

In the end I opted to let the chart overflow instead, to allow the chart to still be relatively easy to read (although the reader will have to scroll left/right to see the rest of the chart).

I think this is an acceptable workaround to allow the rest of the page to fit nicely around a mobile screen. 👍🏽 

But if you have a better alternative, I'm willing to try it out 🙂 .

**Comment by hqtan** [comment]
Hi @OlaShabalina,

I take back what I said earlier!
I found a way to make the stacked bar chart fit in a mobile viewport! 😂 

Here's a screenshot of the `DistanceTravelledModeChart` stacked bar chart in mobile view port:
image

...and the same stacked bar chart in desktop view port:
image

What do you think? 🤞🏽

**Review by OlaShabalina — APPROVED** [review]
Great work @hqtan look much better this way!

**Comment by Amutha37** [comment]
Great work Qing and Olga.👍🏻

**Pull request merged**
