### PR TITLE
Add alt text to all images of the main flow

### PR DESCRIPTION
**Pull request by OlaShabalina**
## Overview of the Pull Request:
Add Alt text to the images on the main survey pages.

Quite interesting research:

1. Started from adding alt text as normal: `alt="XXXXX`, it didn't work. 
2. Tried importing Image from next js:

```js
import Image from 'next/image';

// read in the docs that we have to asign width and height otherwise it might not render as image
<Image src={Q1Cloud} alt="Test Alt Text" width={100} height={100} />
```
it didn't work either , didn't render at all, forget about alt text

3. Tried importing `Img` or`Image` from Chakra and use like this:

```js
// tried with Img then Image separately
import {
  Img,
  Image
} from "@chakra-ui/react";

<Img as={Cloud} alt="Test" />
```
Img was rendered on the page but no alt text applied.

Realised the main issue is that the image is svg, so found another way to add alt-text to icons and use this instead: https://chakra-ui.com/docs/components/icon-button which helpts the screen readers to `give meaning to the button`. That's exactly what we need.

Tested with the scheen reader and it works:

image

## link to Trello card or Github issue
Trello: https://trello.com/c/rJeHHY4I
Git Issue: #218 

## How Has This Been Tested?
- Click on inspect and check if the source code has `aria-label` attribure for images;
- Use the screen reader above (fun experience) and click on the image, sometimes there is a lag when it hasn't finished reading previous text, so click a few times;

## Pull Request Checklist:

Make sure the following checkboxes`[ ]` are checked with `x` before sending your PR -- thank you!

- [x] Have you included a link Trello card / Github issue and written sufficient description to help others review your work?
- [x] Is your pull request up-to-date with `main` branch?
- [x] Have you checked That code is well formatted? Did `npx prettier --check .` return no warnings/errors?
- [x] Have you written instructions on how to test that your changes work as expected?
- [x] Have you tested your work thoroughly on your local machine to ensure you are not breaking anything?

### CODE REVIEW

**Comment by OlaShabalina** [comment]
[[DEV]: Add Alt text to all images](https://trello.com/c/rJeHHY4I/18-dev-add-alt-text-to-all-images)

**Comment by OlaShabalina** [comment]
[[DEV]: Add Alt text to all images](https://trello.com/c/rJeHHY4I/18-dev-add-alt-text-to-all-images)

**Comment by hqtan** [comment]
Awesome work with adding alt text to the images @OlaShabalina ! 🙌🏽 

I'm still in the process of testing the alt text on various browser/device combinations, so please bear with me! I'm learning lots about browser and device accessibility features from testing this PR!

Here are the tests I'm planning on doing (in no particular order)

* Test doing survey on a Desktop browser:
  * test with a screen reader extension/app in firefox
  * test with a screen reader extension/app in a chrome-based browser (Brave)
* Test doing survey on an Android device (Pixel 4a) using [Talkback](https://support.google.com/accessibility/android/answer/6283677):
  * test on firefox app
  * test on chrome based app (Brave)

**Comment by hqtan** [comment]
### Test filling out survey on Android device with TalkBack, with firefox browser
* ❌ TalkBack didn't read out the `aria-label` text in the images 😞 ; in fact, the image itself could not be selected, and the TalkBack completely skipped the images when reading screen 🤔 
* ❌ could not successfully complete survey using TalkBack screen reader 😢 . Wasn't able to proceed past the `WorkFromHomeDays` question in the hybrid flow. **N.B: this broken functionality is NOT due to the changes in this PR; this problem exists in the production survey too.**

**Comment by hqtan** [comment]
### Test filling out survey on Android device with TalkBack, with Brave (Chrome-based) browser
* ✅ TalkBack was able to read out the `aria-label` text in the images! 😂 
* ❌ could not successfully complete survey using TalkBack screen reader 😢 . Wasn't able to proceed past the `WorkFromHomeDays` question in the hybrid flow. **N.B: this broken functionality is NOT due to the changes in this PR; this problem exists in the production survey too.**

**Comment by OlaShabalina** [comment]
Great analysis @hqtan , really in depth, so what is the conclusion? Do we want to deploy it then think about ways to cover other browsers? It worked well for me in Chrome.

**Comment by hqtan** [comment]
Hi @OlaShabalina !

So sorry it's taken me so long to finish reviewing this PR! 🙇🏽 

I've had very little luck finding a screen reader extension that works well in the browsers I use (Brave and Firefox). The ChromeVox screen reader extension that you use didn't work at all in Brave, unfortunately 😢 . 

In light my lack of ability to find a suitable screen reader to test this PR in a desktop browser, I'm gonna approve this for now, as I've delay this PR for long enough 🙇🏽 .

**Review by hqtan — APPROVED** [review]
lgtm 🚀 

Thx again for your efforts @OlaShabalina !
And apologies again for the delay in reviewing this PR 🙇🏽

**Pull request merged**
