### PR TITLE
Changed the svgs directly, not sure it's a good idea.

### PR DESCRIPTION
**Pull request by batteries76**
I'm not sure I like this solution, but it works for now, and frees up the bottle neck around waiting for this to happen.
I think I would rather leave the SVGs as they are and control them through parameters, but then again I'm not sure why this would be a superior solution.
This at least means that the responsive designs that Meng is working on can be smashed out.
Can revisit this over the coming weeks.
Sorry it took so long.

### CODE REVIEW

**Comment by hqtan** [comment]
Hi @batteries76 ,

tbh, I prefer the changes in #25 ; see my [comments in #25](https://github.com/CodeforAustralia/council-emissions-calculator-spike/pull/25#issuecomment-925392259)

But the final say lies with you and @ymloh for frontend matters :bow:

**Comment by ymloh** [comment]
@hqtan @batteries76
While I agree the progress bar looks more prominent overall in #25, the placement of the text is a little off on that one:


- #25 - the text "[x] out of 5" is left aligned for all pages
image
===============
- #26 - the text is centered between the left edge and the cloud graphic, as per the design specs on figma
image
===============
- Design specs, page 2: 



Maybe we should consult with the designers on how linearly scaling both width and height makes the progress bar look too tiny on smaller portrait viewports? I believe this happens on both #25 and #26

**Comment by batteries76** [comment]
Yes, this is getting frustrating @hqtan and @ymloh.
I have played around with a few versions, but the most responsive looked too small in the mobile version, and the ones that looked better cut off parts of the SVG. 
I agree too that Amutha's version looks better in some instances. I think I can make mine a little better just by setting the width at 100%. (I chose 85% a little arbitrarily in the end - sometimes it helped with certain screen sizes)
I'm looking to have another look tomorrow, but this is really dragging on and I'm sorry about that. 
I'd be up for a dev session at some stage over the weekend to do a bit or organising and maybe some pairing to break through some of these issues.

**Comment by hqtan** [comment]
Hi @batteries76 , @ymloh !

Thanks for your feedback! Good spot on the positioning of the text in the progress bar @ymloh ; I totally missed that! :bow:

On closer inspection, I think I can see what's happening in #25 - the [`viewBox` svg settings](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) used there is cropping the progress bar, making it look like the text is no longer centred ...

@Matt, this is indeed turning out to be a prickly puzzle:
- If we linearly scale the progress bar, it will look small on a mobile device
- if we try not to scale the progress bar, we have to perform some cropping, which is also not ideal...

We might have to rethink how we implement the progress bar. Some suggestions:
- extract the 'cloud' icons from each svg; make a generic progress bar with CSS, and position the cloud icon on top of bar accordingly         
- extract the 'cloud' icons from each svg; use Chakra's progress bar, overlay the cloud icon over the bar accordingly
- ... any other suggestions @batteries76 , @ymloh ?

I think the suggestions could be more involved; we might have to leave it as a post-MVP activity.

I'll bring this up with the design folks in slack to discuss options for moving forward.

**Comment by hqtan** [comment]
Hi @batteries76 ,

**Pull request closed without merging**
