### PR TITLE
Form page 1

### PR DESCRIPTION
**Pull request by ymloh**
### Links
[gh-pages link](https://ymloh.github.io/council-emissions-calculator-spike/form/1)
[Trello card](https://trello.com/c/UvQ1Av4x/164-dev-sml-update-page-1-of-form-to-reflect-updated-wireframe)

### Brief
Turn question 1 of the form from (fig.1) to (fig.2)

### Steps taken to meet the brief
1. (made a terrible initial attempt at writing from scratch)
2. realised brief target is basically a redesigned page 2, so used [table from page 2](https://github.com/ymloh/council-emissions-calculator-spike/blob/17b7f7b9ef2cc8188cac141b689ef80c85737c9c/pages/form/2.js#L31-L59) (fig.3) as template
3. created an internal [checkbox component](https://github.com/ymloh/council-emissions-calculator-spike/blob/17b7f7b9ef2cc8188cac141b689ef80c85737c9c/pages/form/1.js#L23-L41) to replace existing radio buttons, with logic to ensure only a maximum of one option remains selected for each day.
4. plugged checkbox components [into the table](https://github.com/ymloh/council-emissions-calculator-spike/blob/17b7f7b9ef2cc8188cac141b689ef80c85737c9c/pages/form/1.js#L64-L67)
5. added [back button](https://github.com/ymloh/council-emissions-calculator-spike/blob/17b7f7b9ef2cc8188cac141b689ef80c85737c9c/pages/form/1.js#L75-L85) with svg arrow (fig.4)
6. added Chakra UI [variant option in the existing LinkButton component](https://github.com/ymloh/council-emissions-calculator-spike/blob/0c44a19c4ad8ec9c3ffd2cae3b16c07a23d5010f/components/LinkButton/LinkButton.jsx#L13). Variant can be specified in component's props, otherwise defaults to "solid" so as not to break existing usage of LinkButton.

### Fig.4
Figure 4

### CODE REVIEW

**Review by batteries76 — CHANGES_REQUESTED** [review]
Hi Meng @ymloh
Great job! This is looking really good!
When I run it locally I'm having a scrolling issue some of the page is cut-off at the top and bottom. Will investigate this arvo. What I can see of the page is very good. It also could easily be something that I'm doing that is causing the issue, so I want to see about that first.
Perhaps there could be a time for us to go through the code by sharing screens either way.

I'm also starting to think that now might be a good time to work from the outside in. This is more of a general comment. We have the finished designs, so we can make the layout including the header, and then pass in the various pages to that layout, whereas the way it's written now we just have each page acting quite independently. Might be worth a chat because if we move in that direction we might have something looking a bit like the designs by Wednesday. 
Just my opinion though - happy to hear what others think.

**Comment by hqtan** [comment]
Hi @ymloh ,
Nice work on your first PR to this repo! :hand:
Re @batteries76 's comment:
> When I run it locally I'm having a scrolling issue some of the page is cut-off at the top and bottom. 

I don't get the page cut off on the top _and_ bottom when running app with @ymloh's changes locally. But what I have consistently observed, both locally and on [@ymloh's github page](https://ymloh.github.io/council-emissions-calculator-spike/form/1), is that the title and question on top no longer displays when I either:
- resized my browser window to a short height, or
- when viewing page in a browser on a mobile device.
I was still able to see and click on the 'Back' and 'Continue' button at the bottom in both cases.

Below is a full page screenshot of what I observed in a resized browser window. N.B: It isn't a screenshot of a _portion_ of page...
image

But I suspect this problem was not introduced in this PR. I see similar issues happening on main branch of CfA repo (see https://codeforaustralia.github.io/council-emissions-calculator-spike/form/2 in a small browser window to replicate the same issue). I think it's a pre-existing bug. And it's one we should look into separately. I'll raise a git issue to address this bug.

I also noticed an issue when clicking on the 'Back' button [in page 1 of @ymloh's github page](https://ymloh.github.io/council-emissions-calculator-spike/form/1): it takes me to https://ymloh.github.io/council-emissions-calculator-spike/form/3 for some reason :shrug: (I got the same behaviour while in incognito mode in a different browser). This didn't happen when I tested the changes locally. I dunno if that's reproducible on a different person's browser!

Re @batteries76 's comment:
> I'm also starting to think that now might be a good time to work from the outside in.

Yes, I concur! We should revisit the `Layout` component :+1: . I would be keen to be involved in that chat! Happy to try and catchup before Wednesday if ppl are up for it, but no rush :slightly_smiling_face:.

**Comment by batteries76** [comment]
Hi Qing @hqtan,
All really good thorough analysis of the issues. 
I should have checked the comments after putting my little one to bed because I ended up jumping on an unplanned call with Meng for a brief chat, and I gave him the option to investigate the `Layout` component for exact the reasons that you describe above. Nothing more than a bit of a look to see what might happen if he puts the header in there and takes off some of the CSS that I suspect is restricting the child components. I asked Meng to write a ticket on Trello if he was tackling it.
He might not get to it, and if he didn't I was maybe going to have a look tomorrow night myself. The thinking was that if this one falls out in a reasonable time then we might have a shot at having the whole thing looking ok by Wednesday night, which would be a decent reason for a party with pizza. Still - not pressure, just a loose goal. I know things don't often work out like that. If we don't have time or it's hard, all good.
How does that sound to you? 
If we do end up chatting tomorrow night we will let you know so you can be around.

**Comment by hqtan** [comment]
Hi @ymloh , @batteries76,

Sounds like an interesting chat; Keep me in the loop plz! I might not always be able to make it, but I'll try to attend the chats!

I think the `Layout` update work is a separate task, so let's wrap this one up! 

@ymloh , I'm gonna approve this PR; feel free to merge it when you're ready! :+1:

**Review by hqtan — APPROVED** [review]
Mr Miyagi approves

**Pull request merged**
