### PR TITLE
form page 3

### PR DESCRIPTION
**Pull request by ymloh**
[Trello card](https://trello.com/c/73XNVrEa/166-dev-sml-update-page-3-of-form-to-reflect-updated-wireframe)

Implemented @batteries76's suggestions for cleaning up the Back and Continue buttons, and it worked wonders:
- [much cleaner Button code on Question3.js](https://github.com/ymloh/council-emissions-calculator-spike/blob/b6f2fbce839c0e7c0d41fdc323fb5c83694db06c/pages/form/Question3.js#L39-L42)
- [less complex implementation of the buttons themselves](https://github.com/ymloh/council-emissions-calculator-spike/blob/b6f2fbce839c0e7c0d41fdc323fb5c83694db06c/components/LinkButton/LinkButton.jsx#L22-L36)

### CODE REVIEW

**Comment by hqtan** [comment]
Hi @ymloh !

Love the simpler implementation of the 'Back' and 'Continue' Buttons!
Also, nice work on making SVG images into components! It does make the code in `pages/form/Question3.js` look less cluttered :slightly_smiling_face: :+1:

**Review by hqtan — APPROVED** [review]
cowabunga dude

**Review by ymloh — COMMENTED** [review]
Sorry, only just saw that the check to disable the continue button wasn't in. All good now (I hope)

**Review by batteries76 — APPROVED** [review]
Great work Meng! Qing likes it, as do I, so we are go.

**Comment by hqtan** [comment]
[DEV: [SML] update page 3 of form to reflect updated wireframe](https://trello.com/c/73XNVrEa/166-dev-sml-update-page-3-of-form-to-reflect-updated-wireframe)

**Pull request merged**
